const { createGlobPatternsForDependencies } = require('@nx/angular/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {
      colors: {
        background: '#101414',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'inverse-on-surface': '#2d3131',
        'inverse-primary': '#006a6a',
        'inverse-surface': '#e0e3e2',
        'on-background': '#e0e3e2',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-primary': '#003737',
        'on-primary-container': '#00fbfb',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f4f',
        'on-secondary': '#1b3534',
        'on-secondary-container': '#cce8e7',
        'on-secondary-fixed': '#051f1f',
        'on-secondary-fixed-variant': '#324b4b',
        'on-surface': '#e0e3e2',
        'on-surface-variant': '#dae5e4',
        'on-tertiary': '#502400',
        'on-tertiary-container': '#ffdcc7',
        'on-tertiary-fixed': '#311300',
        'on-tertiary-fixed-variant': '#723600',
        outline: '#889392',
        'outline-variant': '#3f4948',
        primary: '#00dddd',
        'primary-container': '#004f4f',
        'primary-fixed': '#00fbfb',
        'primary-fixed-dim': '#00dddd',
        scrim: '#000000',
        secondary: '#b0cccb',
        'secondary-container': '#324b4b',
        'secondary-fixed': '#cce8e7',
        'secondary-fixed-dim': '#b0cccb',
        shadow: '#000000',
        surface: '#101414',
        'surface-bright': '#363a39',
        'surface-container': '#1c2020',
        'surface-container-high': '#272b2a',
        'surface-container-highest': '#313635',
        'surface-container-low': '#191c1c',
        'surface-container-lowest': '#0b0f0e',
        'surface-dim': '#101414',
        'surface-tint': '#00dddd',
        'surface-variant': '#3f4948',
        tertiary: '#ffb787',
        'tertiary-container': '#723600',
        'tertiary-fixed': '#ffdcc7',
        'tertiary-fixed-dim': '#ffb787',
        'neutral-variant20': '#293232',
        neutral10: '#191c1c',
      },
    },
  },
  plugins: [],
};
